/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Home: typeof import('./components/Home/home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarHeader: typeof import('./components/sidebar/sidebarHeader.vue')['default']
    SidebarIcon: typeof import('./components/sidebar/sidebarIcon.vue')['default']
    SidebarItem: typeof import('./components/sidebar/sidebarItem.vue')['default']
  }
}
