/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BinaryAdditionPractice: typeof import('./components/DataStorage/BinaryAdditionPractice.vue')['default']
    BinaryMultiplicationPractice: typeof import('./components/DataStorage/BinaryMultiplicationPractice.vue')['default']
    BinaryToDecimalPractice: typeof import('./components/DataStorage/BinaryToDecimalPractice.vue')['default']
    BinaryToHexPractice: typeof import('./components/DataStorage/BinaryToHexPractice.vue')['default']
    BinaryToOctalPractice: typeof import('./components/DataStorage/BinaryToOctalPractice.vue')['default']
    DataStorageMenu: typeof import('./components/DataStorage/DataStorageMenu.vue')['default']
    DecimalToBinaryPractice: typeof import('./components/DataStorage/DecimalToBinaryPractice.vue')['default']
    DecimalToHexadecimalPractice: typeof import('./components/DataStorage/DecimalToHexadecimalPractice.vue')['default']
    DecimalToOctalPractice: typeof import('./components/DataStorage/DecimalToOctalPractice.vue')['default']
    FindHypotenuse: typeof import('./components/Trigonometry/RightAngle/FindHypotenuse.vue')['default']
    Grade10Menu: (typeof import("./components/Trigonometry/Grade10Menu.vue"))["default"]
    HelloWorld: (typeof import("./components/HelloWorld.vue"))["default"]
    HexadecimalToDecimalPractice: typeof import('./components/DataStorage/HexadecimalToDecimalPractice.vue')['default']
    HexToBinaryPractice: typeof import('./components/DataStorage/HexToBinaryPractice.vue')['default']
    Home: (typeof import("./components/Home/home.vue"))["default"]
    HomeView: typeof import('./components/Home/HomeView.vue')['default']
    OctalToBinaryPractice: typeof import('./components/DataStorage/OctalToBinaryPractice.vue')['default']
    OctalToDecimalPractice: typeof import('./components/DataStorage/OctalToDecimalPractice.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarHeader: typeof import('./components/sidebar/sidebarHeader.vue')['default']
    SidebarIcon: typeof import('./components/sidebar/sidebarIcon.vue')['default']
    SidebarItem: typeof import('./components/sidebar/sidebarItem.vue')['default']
    TrigonometryMenu: typeof import('./components/Trigonometry/TrigonometryMenu.vue')['default']
  }
}
