/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/DataStorage/BinaryAddition': RouteRecordInfo<'/DataStorage/BinaryAddition', '/DataStorage/BinaryAddition', Record<never, never>, Record<never, never>>,
    '/DataStorage/BinaryMultiplication': RouteRecordInfo<'/DataStorage/BinaryMultiplication', '/DataStorage/BinaryMultiplication', Record<never, never>, Record<never, never>>,
    '/DataStorage/BinaryToDecimal': RouteRecordInfo<'/DataStorage/BinaryToDecimal', '/DataStorage/BinaryToDecimal', Record<never, never>, Record<never, never>>,
    '/DataStorage/BinaryToOctal': RouteRecordInfo<'/DataStorage/BinaryToOctal', '/DataStorage/BinaryToOctal', Record<never, never>, Record<never, never>>,
    '/DataStorage/DataStorage': RouteRecordInfo<'/DataStorage/DataStorage', '/DataStorage/DataStorage', Record<never, never>, Record<never, never>>,
    '/DataStorage/DecimalToBinary': RouteRecordInfo<'/DataStorage/DecimalToBinary', '/DataStorage/DecimalToBinary', Record<never, never>, Record<never, never>>,
    '/DataStorage/DecimalToHexadecimal': RouteRecordInfo<'/DataStorage/DecimalToHexadecimal', '/DataStorage/DecimalToHexadecimal', Record<never, never>, Record<never, never>>,
    '/DataStorage/DecimalToOctal': RouteRecordInfo<'/DataStorage/DecimalToOctal', '/DataStorage/DecimalToOctal', Record<never, never>, Record<never, never>>,
    '/DataStorage/HexadecimalToDecimal': RouteRecordInfo<'/DataStorage/HexadecimalToDecimal', '/DataStorage/HexadecimalToDecimal', Record<never, never>, Record<never, never>>,
    '/DataStorage/OctalToDecimal': RouteRecordInfo<'/DataStorage/OctalToDecimal', '/DataStorage/OctalToDecimal', Record<never, never>, Record<never, never>>,
  }
}
